### ISSUE TITLE
dict: ref in usg[type="geographic" not allowed

### ISSUE THREAD

**Issue by VeronikaEngler** [acdh-oeaw/shawi-data#75] opened 2024-09-06 12:31 UTC
This error occurs in

DShaAr.staahal_000
DShaAr.bidd_000
DShaAr.birza_001
DShaAr.yibra_lig_gimal_000
DShaAr.yibra_lig_gimal_000

**Comment by dasch124** [comment] 2024-09-10 11:44
Duplicate of #39

**Closed by dasch124** 2024-09-10 11:45 UTC
Labels: dictionary
